notify:
  status: true
  monitor: '0 9 * * *'
  sync: '0 21 * * *'
  notify_path: 'backup'
  refresh_token: ''

wechat:
  corp_id: ""
  secret: ""
  agent_id: ""
  to_user: ""
  proxy_url: ""
  image_url: ""

